---
- name: get original
  local_action: raw
    ssh root@{{ inventory_hostname }} 'cat /etc/rc.local' > /tmp/rc.local
  changed_when: false

- name: template
  local_action: template
    src=rc.local
    dest=/tmp/rc.local
    mode=644
  notify:
    reboot

- name: copy
  local_action: raw
    cat /tmp/rc.local | ssh root@{{ inventory_hostname }} 'cat > /etc/rc.local'
  changed_when: false
